### ISSUE TITLE
disk quota error

### ISSUE THREAD

**Issue by Jordan231111** [kmille36/PWD-Windows-2022#1]
docker: Error response from daemon: symlink libheimntlm.so.0.1.0 /var/lib/docker/vfs/dir/2501d3c7327d706d5bce8dcba704d77c3faa90aafa2e770af3c2948b13104dcd-init/usr/lib/x86_64-linux-gnu/libheimntlm.so.0: disk quota exceeded.

**Comment by kmille36** [comment]
IF IT GOT ANY ERROR, CLOSE PWD SESSION AND START AGAIN
